### ISSUE TITLE
관리자 페이지 개발 및 Editior 선정

### ISSUE THREAD

**Issue by KwonTF** [KwonTF/blog#12]
BE 개발 전에 Editor를 먼저 선정해야 할 것 같음.
이거 하고 난 이후에 데이터 BE와 연동 해야할것같기에 관리자 페이지를 우선적으로 작업하고 추후 BE와 동시 작업 하는걸로

#### 게시글 작성, 관리
글 작성은 관리자 페이지에서만 한다. 
수정도 게시글 관리에서 진행한다,

#### 회원 관리
현 시점에서 마이너한 기능이지만 하나 만들어 놓긴 한다. 간단히 조회만 하는 페이지로

#### 게시글 통계
간단히 통계낼수 있다면 통계 내는걸로. 조회수 같은건 구현방안 모색중

## Editor

네이버 블로그 같은 글에 사진묶음을 중간중간에 넣어주는 형식을 목표로 함.

### Gatsby
간단하게 블로그를 만들수 있게 도와줌. 마크다운 블로그 예시는 많음.
개츠비는 마크다운 블로그를 만드는 용도보다는 미리 정적인 페이지를 만들어서 뿌려주는 역할을 하는것 같음. 자체적으로 GQL서버를 사용해서 게시글을 저장해놓는것 같은데 연구가 필요.

### [MDX](https://mdxjs.com/)
마크다운 + JSX의 결합
서버에 데이터를 저장하기에 이것만큼 좋은것도 없을거 같긴 함. Gatsby와의 결합이 가능하다고 함

### [NaverSmartEditor2](https://github.com/naver/smarteditor2)
기본적인 블로그 글을 작성할 수 있게 도와줌. 플러그인 삽입이 애매하지만 현 목적에 가장 부합한 요소.
하지만 관리가 되지 않고 2019년 이후로 업데이트가 끊겼다. 설치하는방식도 일반적으로 설치하는게 아니라 파일 받아서 직접 파일 이동시키고 그래야 한다. 불편.

### [CKEditor5](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)
이전에 사용해본 Quill과 같은 맥락을 가진 편집기인듯. 
하지만 마크다운 전용 에디터인듯 하다. 그러나 여러가지 플러그인을 자체적으로 삽입할 수도 있는듯 하다.

**Comment by KwonTF** [comment]
## 결론

CKEditor5 사용하기로함

- 내가 원하는 HTML의 출력을  생성해줌
- 사실 네이버 코드에디터처럼 다양한 기능은 필요 없고 글씨색 지정, 가운데정렬정도만 지원해주면 땡큐인데 다 지원해 주는듯
- Data Model 형식으로 반환해줘서 상당히 깔끔한 데이터가 리턴됨

고려해야 할 점

- 플러그인을 자체적으로 생성해줌. FlickinkCard 묶음을 지정해주거나 처리할 수 있을것 같음.
- 일단 별도의 구분자를 추가해 데이터를 생성하고 플러그인으로의 변환은 추후 다른 이슈에서 처리하는것으로
- HTML을 리액트로 바꾸는것까진 될거같은데 HTML에서 특정 컨텐츠를 리액트 컴포넌트로 변환하는게 될지는 모르겠음

**Comment by niceb5y** [comment]
혹시나 해서 몇가지 에디터 선택지 끄적여보자면...
[TinyMCE](https://www.tiny.cloud/tinymce/) - CKEditor처럼 꽤 유명한 물건
[Draft.js](https://draftjs.org) - 페북에서 만든 리액트용 에디터
[Toast UI Editor](https://github.com/nhn/tui.editor) - NHN에서 만든 에디터
[Editor.js](https://editorjs.io) - 노션 처럼 블럭 단위 에디터

뭐 이미 정했으니 상관없겠지만서도...

**Comment by KwonTF** [comment]
@niceb5y 지금봄 ㅋㅋ
TinyMCE는 진짜 대박인데? 
이건 서버사이드 렌더링 해보고 이걸로 지금 바꾸던가 해야할거 같음. CK에디터는 서버사이드 렌더시 에러뜨고 패키지 집어넣기 너무 그지같아서 바꾸고 싶긴 했음

**Comment by niceb5y** [comment]
블로그 만드는걸 그만둔게 아니었다니

**Comment by KwonTF** [comment]
기능개발 대충 완료
